<!--<div class="card nopad">-->
<!--    <div class="cover"></div>-->
<!--    <table class="data" id="dt-1">-->
<!--        <tr class="title">-->
<!--            <td class="fit"><label><input type="checkbox"><span><i class="md-icon">done</i></span></label></td>-->
<!--            <td>Column 1</td>-->
<!--            <td class="fit"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>-->
<!--                <label><input type="checkbox" value="1"><span><i class="md-icon">done</i></span></label>-->
<!--            </td>-->
<!--            <td>Column 1</td>-->
<!--            <td>-->
<!--                <ul class="buttons ripple">-->
<!--                    <li><a><i class="md-icon">edit</i></a></li>-->
<!--                    <li><a><i class="md-icon">delete</i></a></li>-->
<!--                </ul>-->
<!--            </td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>-->
<!--                <label><input type="checkbox" value="2"><span><i class="md-icon">done</i></span></label>-->
<!--            </td>-->
<!--            <td>Column 1</td>-->
<!--            <td>-->
<!--                <ul class="buttons ripple">-->
<!--                    <li><a><i class="md-icon">edit</i></a></li>-->
<!--                    <li><a><i class="md-icon">delete</i></a></li>-->
<!--                </ul>-->
<!--            </td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>-->
<!--                <label><input type="checkbox" value="3"><span><i class="md-icon">done</i></span></label>-->
<!--            </td>-->
<!--            <td>Column 1</td>-->
<!--            <td>-->
<!--                <ul class="buttons ripple">-->
<!--                    <li><a><i class="md-icon">edit</i></a></li>-->
<!--                    <li><a><i class="md-icon">delete</i></a></li>-->
<!--                </ul>-->
<!--            </td>-->
<!--        </tr>-->
<!--    </table>-->
<!--    <script>-->
<!--        $(document).ready(function() {-->
<!--            $dt = new DataTable($("#dt-1"));-->
<!--        })-->
<!--    </script>-->
<!--</div>-->
<div class="columns pad">
    <div class="col-8">
        <div class="card">
            <h4>Chips</h4>
            <p>
                <span class="chip" data-value="1" data-background="https://scontent.fmnl4-2.fna.fbcdn.net/v/t1.0-1/c46.40.526.526/s160x160/13015287_1291482170866300_7242562453580541981_n.jpg?oh=321ac05d2aa1ae9fca405168bd109f54&oe=57B0EE1D" data-icon="background" data-hasButton="true">
                    <span>Juvar Abrera</span>
                </span>
                <span class="chip" data-icon="letter" data-hasButton="true">
                    <span>Juvar Abrera</span>
                </span>
                <span class="chip" data-icon="" data-hasButton="true">
                    <span>Juvar Abrera</span>
                </span>
                <span class="chip" data-icon="letter" data-hasButton="true">
                    <span>Juvar Abrera</span>
                </span>
                <span class="chip" data-icon="letter" data-hasButton="true">
                    <span>Juvar Abrera</span>
                </span>
            </p>
        </div>
        <div class="card">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam consequuntur corporis esse exercitationem minima quidem repellat. Amet aperiam aspernatur, culpa cumque cupiditate dignissimos doloremque eveniet excepturi facilis ipsum iure maiores molestias nulla officia officiis possimus qui quibusdam quisquam repudiandae velit? Adipisci autem beatae commodi culpa cumque distinctio dolores ducimus eius enim et expedita inventore laborum, laudantium libero minus nam nemo nostrum omnis, pariatur perferendis, placeat possimus provident quae quas quis repellat sapiente sed sequi temporibus totam velit veniam voluptate voluptatum? Accusamus aspernatur odio quia reiciendis. Ad amet aspernatur consequatur delectus ex hic ipsum, magni, minus necessitatibus nihil optio porro saepe?</p>
            <h4>Progress</h4>
            <div class="progress">
                <div class="indeterminate"></div>
            </div>
        </div>
        <div class="card">
            <h4>Hehe</h4>
            <div class="data-action-card">
                <div class="table">
                    <div class="row">
                        <div class="cell middle">
                            <span class="data-label"></span>
                        </div>
                        <div class="cell fit">
                            <ul class="nav">
                                <li><a><span><i class="md-icon">select_all</i></span></a></li>
                                <li><a><span><i class="md-icon">clear</i></span></a></li>
                                <li><a><span><i class="md-icon">more_vert</i></span></a>
                                    <ul class="menu">
                                        <li><a><span><i class="md-icon">delete</i>Delete</span></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <table class="data" id="dt-1">
                <tr class="title">
                    <td class="fit">
                        <label><input type="checkbox"><span><i class="md-icon">done</i></span></label>
                    </td>
                    <td>Column 1</td>
                    <td class="fit"></td>
                </tr>
                <tr>
                    <td>
                        <label><input type="checkbox" value="1"><span><i class="md-icon">done</i></span></label>
                    </td>
                    <td>Column 1</td>
                    <td>
                        <ul class="buttons ripple">
                            <li><a><i class="md-icon">edit</i></a></li>
                            <li><a><i class="md-icon">delete</i></a></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label><input type="checkbox" value="2"><span><i class="md-icon">done</i></span></label>
                    </td>
                    <td>Column 1</td>
                    <td>
                        <ul class="buttons ripple">
                            <li><a><i class="md-icon">edit</i></a></li>
                            <li><a><i class="md-icon">delete</i></a></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label><input type="checkbox" value="3"><span><i class="md-icon">done</i></span></label>
                    </td>
                    <td>Column 1</td>
                    <td>
                        <ul class="buttons ripple">
                            <li><a><i class="md-icon">edit</i></a></li>
                            <li><a><i class="md-icon">delete</i></a></li>
                        </ul>
                    </td>
                </tr>
            </table>
            <script>
                $(document).ready(function() {
                    $dt = new DataTable($("#dt-1"));
                })
            </script>
        </div>
    </div>
    <div class="col-4">
        <div class="card" id="card-1">
            <h4>Hello</h4>
            <div class="cover"></div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, repellat.
                <label><span>Hello</span><input type="text"></label>
                <label><span>Hello</span><input type="password"></label>
                <label><span>Hello</span><input type="time"></label>
                <label><span>Hello</span><input type="date"></label>
                <label class="switch"><input type="checkbox"><span><i></i></span></label>
                <label><span>Hello</span><select name="">
                        <option value="1">2</option>
                        <option value="3">4</option>
                    </select></label>
                <label for=""><span>Hello</span><textarea></textarea></label>
            </p>
            <ul class="buttons right ripple">
                <li><a onclick="$dt.dumpData();" class="flat_button">Ok</a></li>
                <li><a href="#" class="raised_button">Ok</a></li>
                <li><a href="#" class="raised_button">Ok</a></li>
            </ul>
        </div>
    </div>
</div>